FROM latex:minimal

# extras
RUN apt-get update
#RUN apt-get install -y --no-install-recommends \
#    dvipng \
#    ghostscript \
#    fonts-dejavu \
#    texlive \
#    texlive-latex-recommended \
#    texlive-science \

# poster
RUN apt-get install -y \
    fonts-lato \
    lmodern \
    texlive-luatex \
    && \
    luaotfload-tool --update
# last line above builds font caches

RUN apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* \
    && apt-get autoremove -y

CMD ['bash']
